Repository vanilla/addons, pull requests merged in 2019-02, with the labels that each got.

#687 Update licenses and versions for open source release
  plugins/AuthorSelector/addon.json
  plugins/CivilTongueEx/addon.json
  plugins/FeedDiscussions/addon.json
  plugins/FileUpload/addon.json
  plugins/ForumMerge/addon.json
  plugins/Ignore/addon.json
  plugins/LastEdited/addon.json
  plugins/MathJax/LICENSE.md
  plugins/MathJax/addon.json
  plugins/Multilingual/addon.json
  plugins/NBBC/addon.json
  plugins/QnA/addon.json
  plugins/Redirector/addon.json
  plugins/RoleTitle/addon.json
  plugins/ShareThis/addon.json
  plugins/Sitemaps/addon.json
  plugins/Spoof/addon.json
  plugins/debugbar/LICENSE.md
  plugins/debugbar/addon.json
  plugins/jsconnect/addon.json
  plugins/necro/addon.json
Labels: Status: Needs Backport

#655 Add cache options to SQL driver to cache getProviders query response
  plugins/jsconnect/class.jsconnect.plugin.php
Labels: Status: Revision Needed

#689 QnA: Change permission to AcceptAnswer to Garden.Curation.Manage
  plugins/QnA/class.qna.plugin.php
Labels: Domain: Addons, Domain: Roles & Permissions
